ProTwo/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from appTwo import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^users/',include('appTwo.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^appTwo/',include('appTwo.urls'))
]

appTwo/urls.py
from django.conf.urls import url
from appTwo import views
app_name = 'appTwo'

urlpatterns = [
    url(r'^users/$',views.users,name='users'),
    url(r'^index/$',views.index,name = 'index'),
    url(r'^login/$',views.login,name = 'login'),
    url(r'^validation1/$',views.validation1,name = 'validation1'),
    url(r'^$',views.validation2,name = 'validation2'),
    url(r'^validation3/$',views.validation3,name = 'validation3'),
    url(r'^validation4/$',views.validation4,name = 'validation4'),
    url(r'^validation5/$',views.validation5,name = 'validation5'),
    url(r'^validation6/$',views.validation6,name = 'validation6'),
    url(r'^validation7/$',views.validation7,name = 'validation7'),
    url(r'^validation8/$',views.validation8,name = 'validation8'),
    url(r'^validation9/$',views.validation9,name = 'validation9'),
    url(r'^statistics/$',views.statistics,name='statistics'),
    url(r'^signup_next1/$',views.signup_next1,name='signup_next1'),
    url(r'^validation10/$',views.validation10,name = 'validation10'),
    url(r'^validation11/$',views.validation11,name = 'validation11'),
    url(r'^validation12/$',views.validation12,name = 'validation12'),
    url(r'^NewSmartCard/$',views.NewSmartCard,name = 'NewSmartCard'),
]

appTwo/models.py
from django.db import models


# Create your models here.

class User(models.Model):
    first_name = models.CharField(max_length=128)
    last_name = models.CharField(max_length=128)
    email = models.EmailField(max_length=254,unique=True)
    Aadhaar_number = models.IntegerField(default = 0)
    def __str__(self):
    	return self.first_name
class Login(models.Model):
    username = models.CharField(max_length=128)
    password = models.CharField(max_length=128)
    def __str__(self):
    	return self.username

appTwo/forms.py
from django import forms
from appTwo.models import User
from appTwo.models import Login


class NewUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = '__all__'
class NewLoginForm(forms.ModelForm):
    class Meta:
        model = Login
        fields = '__all__'

appTwo/views.py
from django.shortcuts import render
from django.http import HttpResponse
from appTwo.forms import NewUserForm
from appTwo.forms import NewLoginForm
#from appTwo.models import User
# Create your views here.

def index(request):
    return render(request,'apptwo/index.html')

def users(request):

    form = NewUserForm()
    if request.method == "POST":
        form = NewUserForm(request.POST)

        if form.is_valid():
            form.save(commit = True)
            return render(request,'appTwo/signup_next.html')
        else:
            print("ERROR form invalid")
    return render(request,'appTwo/users.html',{'form':form})
def relative(request):
    return render(request,'appTwo/relative_url.html')
def login(request):
    formLogin = NewLoginForm()
    if request.method == "POST":
        formLogin = NewLoginForm(request.POST)

        if formLogin.is_valid():
            formLogin.save(commit = True)
            return index(request)
        else:
            print("ERROR form invalid")
    return render(request,'appTwo/login.html',{'form1':formLogin})
def validation1(request):
    return render(request,'appTwo/validation1.html')
def validation2(request):
    return render(request,'appTwo/validation2.html')
def validation3(request):
    return render(request,'appTwo/validation3.html')
def validation4(request):
    return render(request,'appTwo/validation4.html')
def validation5(request):
    return render(request,'appTwo/validation5.html')
def validation6(request):
    return render(request,'appTwo/validation6.html')
def validation7(request):
    return render(request,'appTwo/validation7.html')
def validation8(request):
    return render(request,'appTwo/validation8.html')
def validation9(request):
    return render(request,'appTwo/validation9.html')
def statistics(request):
    return render(request,'appTwo/statistics.html')
def signup_next1(request):
    return render(request,'appTwo/signup_next1.html')
def validation10(request):
    return render(request,'appTwo/validation10.html')
def validation11(request):
    return render(request,'appTwo/validation11.html')
def validation12(request):
    return render(request,'appTwo/validation12.html')
def NewSmartCard(request):
    return render(request,'appTwo/NewSmartCard.html')

templates/appTwo/NewSmartCard.html
<!DOCTYPE html>
{% load static%}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light " style="background-color: #0091EA";>
      <h1 class="navbar-brand" style="color:White;">National Voting System</h1>
      <h2 class="navbar-brand" style="color:white;">New Smart Card Registration</h2>
    </nav>
    <div class="container" style="text-align:center;">
      <div class="jumbotron">
      <form  action="" method="post">
        <label>Enter your existing Id Number</label>
        <input type="number" name="" value="ID">
        <input type="submit" name="Submit" value="submit">
      </form>
    </div>
    </div>
  </body>
</html>

templates/appTwo/signup_next.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Signup next</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/users.css" %}">
    <script
    src="https://code.jquery.com/jquery-3.1.1.min.js"
    integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
    crossorigin="anonymous">
    </script>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light " style="background-color: #0091EA";>
      <h1 class="navbar-brand" style="color:White;">National Voting System</h1>
      <h2 style="color:White;">Encryption Status</h2>
    </nav>
    <div class="container">
    <h3>Your details are successfully added into the server</h3>
    <h3>Your data is being encrypted</h3>
  </div>

  <script>
    setTimeout(function(){
       window.location.href = '{% url 'appTwo:signup_next1'%}';
    }, 5000);
</script>
  </body>
</html>

templates/appTwo/signup_next1.html
<!DOCTYPE html>
{% load static%}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/users.css" %}">
    <script
    src="https://code.jquery.com/jquery-3.1.1.min.js"
    integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
    crossorigin="anonymous">
    </script>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light " style="background-color: #0091EA";>
      <h1 class="navbar-brand" style="color:White;">National Voting System</h1>
      <h2 style="color:White;">Encryption Status</h2>
    </nav>
    <div class="container">
    <h3>You will receive your password through registered Email and SMS on your registered mobile number</h3>
    <h3>You will get your smart card through post</h3>
    </div>
    <script>
      setTimeout(function(){
         window.location.href = '{% url 'index'%}';
      }, 5000);
  </script>
  </body>
</html>

templates/appTwo/test.html
<nav class="navbar navbar-expand-lg navbar-light " style="background-color: #0091EA";>
  <h1 class="navbar-brand" style="color:White;">National Voting System</h1>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#" style="color:White;">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'appTwo:users' %}" style="color:White;">NewUserRegistration</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'appTwo:login' %}" style="color:White;">Login</a>
      </li>

    </ul>

  </div>
</nav>

templates/appTwo/users.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Users</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/users.css" %}">
    <style>
        .i-am-centered {
            margin: auto;
            max-width: 300px;
        }
    </style>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light " style="background-color: #0091EA";>
      <h1 class="navbar-brand" style="color:White;">National Voting System</h1>
    </nav>
    <div class="jumbotron">
    <div class="container">
    <h1>Please signup here !</h1>
    <form  method="post">
       <div class="i-am-centered">
      <div class="form-group">
               <label>First Name:</label>
               <br>
               {{ form.first_name }}
           </div>
           <div class="form-group">
               <label>Last Name: </label>
               <br>
               {{ form.last_name }}
           </div>
           <div class="form-group">
               <label>Email Id:</label>
               <br>
               {{ form.email }}
           </div>
           <div class="form-group">
               <label>Aadhaar No:</label>
               <br>
               {{ form.Aadhaar_number }}
           </div>
           </div>
      {% csrf_token %}
      <input type="submit" class = 'btn btn-primary' name="" value="Submit">
    </form>
</div>
</div>
  </body>
</html>

templates/appTwo/validation1.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/validation3.css" %}">
    <style media="screen">
    body{
      background-image: url('{% static "images/Background.jpg"%}');
      background-repeat: no-repeat;
      background-attachment: fixed;
      background-size: cover;
    }
    </style>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light " style="background-color: #0091EA";>
      <h1 class="navbar-brand" style="color:White;">National Voting System</h1>
      <h2 class="navbar-brand" style="color:white;">Biometric verification Process</h2>
    </nav>
    <div class="container">
    <h1>Smart card is being processed , click next to see details</h1>
    <a href="{% url 'appTwo:validation4' %}">NEXT</a>
  </div>
  </body>
</html>

templates/appTwo/validation10.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/validation3_home.css" %}">
  </head>
  <style media="screen">
  body{
    background-image: url('{% static "images/Background.jpg"%}');
    background-repeat: no-repeat;
    background-attachment: fixed;
    background-size: cover;
  }
  </style>
  <script
  src="https://code.jquery.com/jquery-3.1.1.min.js"
  integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
  crossorigin="anonymous">
  </script>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light " style="background-color: #0091EA";>
      <h1 class="navbar-brand" style="color:White;">National Voting System</h1>
      <h2 class="navbar-brand" style="color:white;">Voting Status</h2>
    </nav>
    <div class="container" style="text-align:center;">
      <h1>Your card is being decrypted , please wait for a while you will be redirected to next page </h1>

    </div>
    <script>
      setTimeout(function(){
         window.location.href = '{% url 'appTwo:validation3'%}';
      }, 3000);
  </script>
  </body>
</html>

templates/appTwo/validation11.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/validation3_home.css" %}">
  </head>
  <style media="screen">
  body{
    background-image: url('{% static "images/Background.jpg"%}');
    background-repeat: no-repeat;
    background-attachment: fixed;
    background-size: cover;
  }
  </style>
  <script
  src="https://code.jquery.com/jquery-3.1.1.min.js"
  integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
  crossorigin="anonymous">
  </script>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light " style="background-color: #0091EA";>
      <h1 class="navbar-brand" style="color:White;">National Voting System</h1>
      <h2 class="navbar-brand" style="color:white;">Vote Encryption</h2>
    </nav>
    <div class="container" style="text-align:center;">
      <h1>Your vote is getting encrypted ,you will be redirected.</h1>
    </div>
    <script>
      setTimeout(function(){
         window.location.href = '{% url 'appTwo:validation12'%}';
      }, 3000);
  </script>
  </body>
</html>

templates/appTwo/validation12.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/validation3_home.css" %}">
  </head>
  <style media="screen">
  body{
    background-image: url('{% static "images/Background.jpg"%}');
    background-repeat: no-repeat;
    background-attachment: fixed;
    background-size: cover;
  }
  </style>
  <script
  src="https://code.jquery.com/jquery-3.1.1.min.js"
  integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
  crossorigin="anonymous">
  </script>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light " style="background-color: #0091EA";>
      <h1 class="navbar-brand" style="color:White;">National Voting System</h1>
      <h2 class="navbar-brand" style="color:white;">Vote Encryption</h2>
    </nav>
    <div class="container" style="text-align:center;">
      <h1>You have successfully casted your vote</h1>
      <a href="{% url 'appTwo:index' %}"  >HOME</a>
    </div>

  </body>
</html>

templates/appTwo/validation2.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Vote status</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/validation3.css" %}">
    <style media="screen">
    body{
      background-image: url('{% static "images/Background.jpg"%}');
      background-repeat: no-repeat;
      background-attachment: fixed;
      background-size: cover;
    }
    </style>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light " style="background-color: #0091EA";>
      <h1 class="navbar-brand" style="color:White;">National Voting System</h1>
      <h2 class="navbar-brand" style="color:white;">Voting Status</h2>
    </nav>
<div class="container">
<form  method="post" action="appTwo/validation3.html">
  <h1>Swipe your smart card</h1>
  <a href="{% url 'appTwo:validation10' %}"  >SUBMIT</a>
</form>
</div>
  </body>
</html>

templates/appTwo/validation3.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/validation3_home.css" %}">
  </head>
  <style media="screen">
  body{
    background-image: url('{% static "images/Background.jpg"%}');
    background-repeat: no-repeat;
    background-attachment: fixed;
    background-size: cover;
  }
  </style>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light " style="background-color: #0091EA";>
      <h1 class="navbar-brand" style="color:White;">National Voting System</h1>
      <h2 class="navbar-brand" style="color:white;">Voting Status</h2>
    </nav>
    <div class="container" style="text-align:center;">
      <h1>Your vote status is incomplete </h1>
      <h1>You can vote by going to the Biometric verification section on the home page</h1>
      <a href="{% url 'appTwo:index' %}">HOME</a>
    </div>
  </body>
</html>

templates/appTwo/validation5.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/validation6.css" %}">
    <style media="screen">
    body{
      background-image: url('{% static "images/Background.jpg"%}');
      background-repeat: no-repeat;
      background-attachment: fixed;
      background-size: cover;
    }
    </style>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light " style="background-color: #0091EA";>
      <h1 class="navbar-brand" style="color:White;">National Voting System</h1>
      <h2 class="navbar-brand" style="color:white;">Biometric verification Process</h2>
    </nav>



    <div class="container">
      <div class="r1">
        <div class="c1">
          <h4>Image_1</h4>
          <img id=img1 src="{% static "images/Img_1_1_1.jpg" %}">
        </div>
        <div class="c1">
          <h4>Image_2</h4>
          <img id=img1 src="{% static "images/Img_1_1_2.jpg" %}">
        </div>

        <div class="r2">
          <div class="c2">
            <h4>Image_3</h4>
            <img id=img2 src="{% static "images/Img_1_1_3.jpg" %}">
          </div>
          <div class="c2">
            <h4>Image_4</h4>
            <img id=img2 src="{% static "images/Img_1_1_4.jpg" %}">
          </div>
      </div>
      </div>
      <div class="container" id ="cont1">
      <div class="c3">
        <h4>Image_5</h4>
        <img id=img2 src="{% static "images/Img_1_1_5.jpg" %}">
      </div>
      <h1>                          </h1>
      <a href="{% url 'appTwo:validation6' %}">NEXT</a>
      </div>
  </div>

  </body>
</html>

templates/appTwo/validation6.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/validation7.css" %}">
    <style media="screen">
    body{
      background-image: url('{% static "images/Background.jpg"%}');
      background-repeat: no-repeat;
      background-attachment: fixed;
      background-size: cover;
    }
    </style>
  </head>
  <body>
     <nav class="navbar navbar-expand-lg navbar-light " style="background-color: #0091EA";>
       <h1 class="navbar-brand" style="color:White;">National Voting System</h1>
       <h2 class="navbar-brand" style="color:white;">Biometric verification Process</h2>
     </nav>
     <div class="container">
     <h1>Take a sample of iris from the voter</h1>
     <a href="{% url 'appTwo:validation7' %}">NEXT</a>
     </div>
  </body>
</html>

templates/appTwo/validation9.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/validation9.css" %}">
    <style media="screen">
    body{
      background-image: url('{% static "images/Background.jpg"%}');
      background-repeat: no-repeat;
      background-attachment: fixed;
      background-size: cover;
    }
    </style>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light " style="background-color: #0091EA";>
      <h1 class="navbar-brand" style="color:White;">National Voting System</h1>
      <h2 class="navbar-brand" style="color:white;">Biometric verification Process</h2>
    </nav>
    <div class="container">
      <h1>Processing Your request</h1>
      <a href="{% url 'appTwo:validation7' %}">BACK</a>
    </div>
  </body>
</html>